# Generated by Django 5.0.2 on 2024-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('download_path', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=50)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
